// ======================
// 📘 DATA GURU
// ======================
const dataGuru = [
  "MULTAZAM","ALVIN","ALZAM","HAIDAR","SHAFWAN","FAHMI",
  "KHAIZURAN","MULIA","FAIQ","FAVIAN","KAMAL",
  "MEILISA","FATIMAH","EVITA"
];

// ======================
// 📚 DATA MATA PELAJARAN
// ======================
const dataMapel = [
  "AQIDAH","FIQIH","ADAB","SHIRAH","METODE PENGAJARAN",
  "KEWIRAUSAHAAN","NAHWU","SHARAF","BALAGHAH","TAHSIN","TAHFIZ"
];

// ======================
// 🕌 DATA KELAS & SANTRI
// ======================
window.dataSantri = {
  "Keilmuan Islam & Umum": {
    "Kelas 1A Putra": ["ADITYA PUTRA IBRAHIM","AIRLANGGA AZKA ABQORI","AQIELA MARSYAH","BRILLY HANDRIAN","DARREN ATHAYA","DZIKRI MUDHOFFAR","ELLENO QUTHBIE HERMAWAN","FADIL NURHALIM","GABRIEL AL FATIH","HADINATA SAPUTRA","MIKO VAJAR","M. ALMISKY PRATAMA","M. AQIL RIDHO","M. IZAM SAPUTRA","M. SYAKIR HUTABARAT","M. YASIR AL FAZAR JHIRA","M. ZIYAD ZHAZHA","RAFA"],
    "Kelas 1B Putra": ["MUHAMMAD THOORIQ","JUANDA NUR ILHAM","M. ABIL IRWANSYAH","ALIF SAMUDRA","FAHRY AKBAR RAMDHANI","M. USAMAH","MUHAMAD YUSUF ARROSIYD","ROID AFDAL","ANUGRAH PRATAMA","AHMAD FARHAAN","DEDI SETIADI","MOHAMMAD IKHSAN HAIRULI","ALVIN HERFIANTINO","IHZA TRINANDI","ILHAM","RAKA SEPTIAN","CAHYIS ISZAM","DIKKI KURNIAWAN","M. ARYA MAHDI WAFI EL-FAUZANI","EZA FEBRI AL FADZRI","M. DIRGATAMA","VERY SYACH","RADEN AZAA PANCA PUTRA","FAUZAN IBNI JABAR","REZFY FAKHRYAZKA","SYAHRUL RAMADHAN"],
    "Kelas 2 Putra": ["ABDULLAH MUKTI HAFIDZALLAH","AHMAD RIYADI","AKBAR PRAYOGA","ANDES AFENDRA","BASRI AL HAZIQ ZULFAHMI","CANZA RYANDA HUTASUHUT","DAFFA AL MUSYARI","DANANG PRASDITYA SANTOSO","FAHRIE OKTAVIRANO FITRIS","FAKHRI AL MUZAKKI","FALIZH DAFFA QATRUNNADA","FEBRI GHALIH AL FAROBI","HAFIDZ AL ROZI","HAFIDZ ALRIZKY","ILHAM MUKMIN AL FARABI","LUTHFAN ADZAKI","MAHESA AULIA GIFFARI","M. FADHIL BUANA","M. FAISAL FIKRIANSYAH","M. FIRAAS AL INSYIROH","M. XAVI NF","NABIL NAJMI","NAJMIHADI SYAUQII TAMAAM","NAUFAL AKBAR ALKHATIRI","NIZAM KABISAT","QHEIZAN ALQIZA ARISDA","RENAL MARTIN","REYFAS RAMADHAN","ROHADIN FIRDAUS AL QAUSAR","SATRIO ABIMAYU","TEGAR HIDAYAT","WAHYU REYDINATA","ZAHIR ZIBRAN","ZULFAKIH HAERUNNASIHIN","HABIB RAMADHAN"],
    "Kelas 3 Putra": ["AHMAD MAULANA","ALIF MUHAMMAD YUSUF","ARYA DIFA ALSYA","FARAZH SAYYID PUTRA KENEGA","GHOZY FATURRAHMAN","M. FAQIH HAFIDZALLAH","M. RIJALUL KAMIL","M. AL FALAH","M. ALLAM NUR HUSAIN","M. MARPIN","M. RAID MAHRUS","NAFIS","RAFI RAMADHAN","REYNALDI MALIK IBRAHIM ALFARIDZI","WAFII FADHLURROHMAN"],
    "Kelas 4 Benih Ulama": ["ANGGA PRATAMA PUTRA","MIKA RAHEL YUSUF","MELDI NOVRIANSYAH","MARFEL SAPUTRA","PRAWIRO PUJO TUNGGAL JATI"],
    "Kelas 4 Benih Pengusaha": ["KI AGUS MUHAMMAD ABDULLAH SHIDDIQ AGTSALI"],
    "Kelas 1 Putri": ["PITRI RAMADANI","ADIBA AILA KHANZA","AISYAH NUR KHALIFAH","AISYAH NURUL AULIA","ANISYA SEPTIANI","DAFIA NAFLA SYAKIRA","DINA RUHAYAH","FITRAH KIRANA","INAYAH NOURAH ANINDYA","SHELENA","WINDY WINDARI","ASHIFA FITRI RAMADHONI"],
    "Kelas 2 Putri": ["EARLYTA ARSYFA SALSABILA","GHENIS ANDIENTIAZ","GRINNETA NALANI PUTRI","JESSICA PUTRY AYRA","QELZA RAMADHANI ATH THAHIRAH","WILDA","NESSYA RAMADHANY"],
    "Kelas 3 Putri": ["AMIRAH BALQIS RAHADATUL A'ISYAH","BILQIS NUR ANISAH","NILAM CAHYA","NYAYU MARLITSA ARDHANI"]
  },

  "Bahasa Internasional": {
    "Kelas Abah": ["AHMAD MAULANA","AHMAD RIYADI","AKBAR PRAYOGA","ALIF MUHAMMAD YUSUF","ANDES AFENDRA","ANGGA PRATAMA PUTRA","KI AGUS MUHAMMAD ABDULLAH SHIDDIQ AGTSALI","BASRI AL HAZIQ ZULFAHMI","DANANG PRASDITYA SANTOSO","M. FAQIH HAFIDZALLAH","FEBRI GHALIH AL FAROBI","FALIZH DAFFA QATRUNNADA","HABIB RAMADHAN","M. ALLAM NUR HUSAIN","M. AL FALAH","M. MARPIN","MARFEL SAPUTRA","MELDI NOVRIANSYAH","MIKA RAHEL YUSUF","NAFIS","RAFI RAMADHAN","M. RAID MAHRUS","REYFAS RAMADHAN","RENAL MARTIN","ROHADIN FIRDAUS AL QAUSAR","M. XAVI NF","PRAWIRO PUJO TUNGGAL JATI"],
    "Kelas Haidar": ["NIZAM KABISAT","M. RIJALUL KAMIL","DAFFA AL MUSYARI","ALIF SAMUDRA","WAFII FADHLURROHMAN","EZA FEBRI AL FADZRI","M. ABIL IRWANSYAH","SYAHRUL RAMADHAN","HAFIDZ AL ROZI","HAFIDZ ALRIZKY","NAJMIHADI SYAUQII TAMAAM","IHZA TRINANDI","CAHYIS ISZAM","AHMAD FARHAAN","ARYA DIFA ALSYA","M. FADHIL BUANA","WAHYU REYDINATA","FAHRY AKBAR RAMDHANI","ALVIN HERFIANTINO","M. ARYA MAHDI WAFI EL-FAUZANI","RADEN AZAA PANCA PUTRA","FAUZAN IBNI JABAR","REZFY FAKHRYAZKA","M. FAISAL FIKRIANSYAH","QHEIZAN ALQIZA ARISDA"],
    "Kelas Alvin": ["ADITYA PUTRA IBRAHIM","AIRLANGGA AZKA ABQORI","AQIELA MARSYAH","BRILLY HANDRIAN","DARREN ATHAYA","DZIKRI MUDHOFFAR","ELLENO QUTHBIE HERMAWAN","FADIL NURHALIM","GABRIEL AL FATIH","HADINATA SAPUTRA","MIKO VAJAR","M. ALMISKY PRATAMA","M. AQIL RIDHO","M. IZAM SAPUTRA","M. SYAKIR HUTABARAT","M. YASIR AL FAZAR JHIRA","M. ZIYAD ZHAZHA","RAFA"],
    "Kelas Shafwan": ["FAHRIE OKTAVIRANO FITRIS","FAKHRI AL MUZAKKI","CANZA RYANDA HUTASUHUT","M. DIRGATAMA","LUTHFAN ADZAKI","FARAZH SAYYID PUTRA KENEGA","ZULFAKIH HAERUNNASIHIN","MUHAMAD YUSUF ARROSIYD","ROID AFDAL","MOHAMMAD IKHSAN HAIRULI","ZAHIR ZIBRAN","NABIL NAJMI","DEDI SETIADI","ANUGRAH PRATAMA","SATRIO ABIMAYU","TEGAR HIDAYAT","ABDULLAH MUKTI HAFIDZALLAH","ILHAM","ILHAM MUKMIN AL FARABI","JUANDA NUR ILHAM","RAKA SEPTIAN","M. FIRAAS AL INSYIROH","GHOZY FATURRAHMAN","REYNALDI MALIK IBRAHIM ALFARIDZI","M. USAMAH","MAHESA AULIA GIFFARI","M. THOORIQ","DIKKI KURNIAWAN","VERY SYACH"],
    "Kelas Meilisa": ["PITRI RAMADANI","ADIBA AILA KHANZA","AISYAH NUR KHALIFAH","AISYAH NURUL AULIA","ANISYA SEPTIANI","DAFIA NAFLA SYAKIRA","DINA RUHAYAH","FITRAH KIRANA","INAYAH NOURAH ANINDYA","SHELENA","WINDY WINDARI"],
    "Kelas Fatimah": ["ASHIFA FITRI RAMADHONI","EARLYTA ARSYFA SALSABILA","GHENIS ANDIENTIAZ","GRINNETA NALANI PUTRI","JESSICA PUTRY AYRA","QELZA RAMADHANI ATH THAHIRAH","WILDA","NESSYA RAMADHANY","AMIRAH BALQIS RAHADATUL A'ISYAH","BILQIS NUR ANISAH","NILAM CAHYA","NYAYU MARLITSA ARDHANI"],
    "Kelas Evita": ["PITRI RAMADANI","ADIBA AILA KHANZA","AISYAH NUR KHALIFAH","AISYAH NURUL AULIA","ANISYA SEPTIANI","DAFIA NAFLA SYAKIRA","DINA RUHAYAH","FITRAH KIRANA","INAYAH NOURAH ANINDYA","SHELENA","WINDY WINDARI","ASHIFA FITRI RAMADHONI","EARLYTA ARSYFA SALSABILA","GHENIS ANDIENTIAZ","GRINNETA NALANI PUTRI","JESSICA PUTRY AYRA","QELZA RAMADHANI ATH THAHIRAH","WILDA","NESSYA RAMADHANY","AMIRAH BALQIS RAHADATUL A'ISYAH","BILQIS NUR ANISAH","NILAM CAHYA","NYAYU MARLITSA ARDHANI"]
  },

  "Tahsin & Tahfiz Al-Qur'an": {
    "Tahfiz Putra Abah": ["M. AL FALAH","MIKA RAHEL YUSUF","ANGGA PRATAMA PUTRA","NIZAM KABISAT","M. MARPIN","PRAWIRO PUJO TUNGGAL JATI","MAHESA AULIA GIFFARI","NAJMIHADI SYAUQII TAMAAM","MARFEL SAPUTRA","MELDI NOVRIANSYAH","RENAL MARTIN","AHMAD RIYADI"],
    "Tahfiz Putra Ust. Mulia": ["M. XAVI NF","M. FAQIH HAFIDZALLAH","AHMAD MAULANA","ROHADIN FIRDAUS AL QAUSAR","ARYA DIFA ALSYA","M. ALLAM NUR HUSAIN","ILHAM","HABIB RAMADHAN","M. RAID MAHRUS","FARAZH SAYYID PUTRA KENEGA","RAFI RAMADHAN","DAFFA AL MUSYARI"],
    "Tahfiz Putra Haidar": ["ZULFAKIH HAERUNNASIHIN","NAFIS","ANDES AFENDRA","BASRI AL HAZIQ ZULFAHMI","DANANG PRASDITYA SANTOSO","AKBAR PRAYOGA","FEBRI GHALIH AL FAROBI","ZAHIR ZIBRAN","ALIF MUHAMMAD YUSUF"],
    "Tahfiz Putra Khaizuran": ["FALIZH DAFFA QATRUNNADA","FAKHRI AL MUZAKKI","GHOZY FATURRAHMAN","HAFIDZ ALRIZKY","M. FIRAAS AL INSYIROH","WAFII FADHLURROHMAN","M. RIJALUL KAMIL","KI AGUS MUHAMMAD ABDULLAH SHIDDIQ AGTSALI","REYNALDI MALIK IBRAHIM ALFARIDZI","CANZA RYANDA HUTASUHUT","LUTHFAN ADZAKI"],
    "Tahsin Putra Faiq": ["GABRIEL AL FATIH","M. ZIYAD ZHAZHA","QHEIZAN ALQIZA ARISDA","REYFAS RAMADHAN","VERY SYACH","WAHYU REYDINATA","NAUFAL AKBAR ALKHATIRI","M. FADHIL BUANA","SATRIO ABIMAYU","NABIL NAJMI","FAHRY AKBAR RAMDHANI","ELLENO QUTHBIE HERMAWAN","MUHAMAD YUSUF ARROSIYD","ABDULLAH MUKTI HAFIDZALLAH","ILHAM","HAFIDZ AL ROZI","IHZA TRINANDI","ROID AFDAL","DIKKI KURNIAWAN","MOHAMMAD IKHSAN HAIRULI"],
    "Tahsin Putra Favian": ["AQIELA MARSYAH","REZFY FAKHRYAZKA","ALVIN HERFIANTINO","AHMAD FARHAAN","DEDI SETIADI","AIRLANGGA AZKA ABQORI","SYAHRUL RAMADHAN","RAFA","ADITYA PUTRA IBRAHIM","FADIL NURHALIM","DZIKRI MUDHOFFAR","M. FAISAL FIKRIANSYAH","M. USAMAH","TEGAR HIDAYAT","ANUGRAH PRATAMA","RAKA SEPTIAN","FAHRIE OKTAVIRANO FITRIS","CAHYIS ISZAM","M. THOORIQ","M. SYAKIR HUTABARAT","BRILLY HANDRIAN","M. IZAM SAPUTRA"],
    "Tahsin Putra Fahmi": ["M. YASIR AL FAZAR JHIRA","M. ARYA MAHDI WAFI EL-FAUZANI","RADEN AZAA PANCA PUTRA","M. DIRGATAMA","MIKO VAJAR","M. ALMISKY PRATAMA","HADINATA SAPUTRA"],
    "Tahsin Putra Kamal": ["DARREN ATHAYA","M. AQIL RIDHO","ALIF SAMUDRA","EZA FEBRI AL FADZRI","M. ABIL IRWANSYAH","FAUZAN IBNI JABAR"],
    "Tahfiz Putri Abah": ["WILDA","NESSYA RAMADHANY","GHENIS ANDIENTIAZ","JESSICA PUTRY AYRA","NYAYU MARLITSA ARDHANI","GRINNETA NALANI PUTRI"],
    "Tahfiz Putri Fatimah": ["AMIRAH BALQIS RAHADATUL A'ISYAH","BILQIS NUR ANISAH","NILAM CAHYA","QELZA RAMADHANI ATH THAHIRAH"],
    "Tahsin Putri": ["PITRI RAMADANI","ADIBA AILA KHANZA","AISYAH NUR KHALIFAH","AISYAH NURUL AULIA","ANISYA SEPTIANI","DAFIA NAFLA SYAKIRA","DINA RUHAYAH","FITRAH KIRANA","INAYAH NOURAH ANINDYA","SHELENA","WINDY WINDARI","ASHIFA FITRI RAMADHONI","EARLYTA ARSYFA SALSABILA"]
  }
};







